import { RuleAction, RuleCondition, SpendRule } from "./types";

/**
 * Compile a single condition to a JS boolean expression.
 * Runtime variables: amount (number), merchant (string), hour (number)
 */
export function compileCondition(cond: RuleCondition): string {
	const { field, op, value } = cond;

	if (field === "merchant" && op === "contains") {
		const escaped = String(value).replace(/'/g, "\\'");
		return `merchant.includes('${escaped}')`;
	}

	const numVal = Number(value);
	switch (op) {
		case "gt":
			return `${field} > ${numVal}`;
		case "lt":
			return `${field} < ${numVal}`;
		case "gte":
			return `${field} >= ${numVal}`;
		case "lte":
			return `${field} <= ${numVal}`;
		case "eq":
			if (field === "merchant") {
				const escaped = String(value).replace(/'/g, "\\'");
				return `merchant === '${escaped}'`;
			}
			return `${field} === ${numVal}`;
		default:
			return "false";
	}
}

/**
 * Compile an array of conditions to a single AND expression.
 */
export function compileConditions(conditions: RuleCondition[]): string {
	if (conditions.length === 0) return "true";
	return conditions.map(compileCondition).join(" && ");
}

/**
 * Compile a single action to a JS statement.
 */
function compileAction(action: RuleAction): string {
	if (action.type === "block") {
		return `    return false;`;
	}
	const channel = action.channel ?? "push";
	return `    console.log('[notify:${channel}] Rule triggered');`;
}

/**
 * Compile a single SpendRule to a JS if-block string.
 */
export function ruleToCode(rule: SpendRule): string {
	const condExpr = compileConditions(rule.conditions);
	const actionLines = rule.actions.map(compileAction).join("\n");

	const lines = [
		`  // Rule: ${rule.label}`,
		`  if (${condExpr}) {`,
		actionLines,
		rule.stopProcessing && !rule.actions.some((a) => a.type === "block")
			? `    return true; // stopProcessing`
			: null,
		`  }`,
	].filter(Boolean);

	return lines.join("\n");
}

/**
 * Compile all active rules into a complete Investec before_transaction function.
 * Rules are sorted by priority (ascending = lower number runs first).
 */
export function compileRules(rules: SpendRule[]): string {
	const active = rules
		.filter((r) => r.active)
		.sort((a, b) => a.priority - b.priority);

	if (active.length === 0) {
		return `// before_transaction hook — no active rules
const beforeTransaction = (transaction) => {
  return true;
};`;
	}

	const ruleBodies = active.map(ruleToCode).join("\n\n");

	return `// Auto-generated by SpendGate — do not edit manually
// Generated: ${new Date().toISOString()}

const beforeTransaction = (transaction) => {
  const amount   = transaction.centsAmount / 100;
  const merchant = transaction.merchant?.name?.toLowerCase?.() ?? "";
  const hour     = new Date(transaction.dateTime).getHours();

${ruleBodies}

  return true;
};`;
}
